### ISSUE TITLE
Turkish Language PLZ

### ISSUE THREAD

**Issue by Medullitus** [MKSherbini/obsidian-noor#1]
Hello,

Thank you so much for the plugin. Can you please add the Turkish language support?

**Comment by MKSherbini** [comment]
SA, I'm glad you like it.

It's already supported, just make sure to pick `tr` in the settings
![image](https://github.com/MKSherbini/obsidian-noor/assets/50295916/a850b4ec-290d-4f5d-9334-1ad5dd356790)
![image](https://github.com/MKSherbini/obsidian-noor/assets/50295916/4c1fbb68-06ed-452a-9248-95503f29c451)
